name: mirai_app
description: A single hub app for CS/IT students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  google_sign_in: ^6.2.1

  # UI & State Management
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  lottie: ^3.1.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  # Utilities
  url_launcher: ^6.2.4
  share_plus: ^12.0.1
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
